name: midas
description: midas
publish_to: "none"
version: 1.0.0+1




flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand.ttf
       

environment:
  sdk: ">=3.3.1 <4.0.0"



dependencies:
  fl_chart: ^0.36.0


  
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

